### PR TITLE
Added disable button to stop the madness.

### PR DESCRIPTION
**Pull request by troygidney**

### CODE REVIEW

**Comment by troygidney** [comment]
I have already noticed that after a while the redirect rule gets reinstated even with the value stored in storage. But it is 6 am. It is now a tomorrow issue.

**Comment by Oluwaseunus** [comment]
Are there any plans to merge/update this PR? Others like myself would also prefer a button to temporarily toggle off the extension rather than deactivating it entirely.

**Comment by troygidney** [comment]
I doubt it, it's been well over 6 months, and they have to of seen the pull request. And there's now conflicts to the code. 


I recommend you fork the repo, make your changes and run it as your own cause this repo is dead.

**Comment by The-CodingSloth** [comment]
thanks for reminding me. That's my fault lol. Made the updates for this feature and I'll upload it to the web store

**Pull request closed without merging**
